### ISSUE TITLE
Heart Rate Mi band 5 not working on Followers phones

### ISSUE THREAD

**Issue by henriquejourdan** [bigdigital/watchdrip#1]
Hi
First of thanks for all your work Xdrip and watchdrip
I can not share heart rate among any xdrip follower  or nighscout, master OK.
Greetings
Luis Proença

**Comment by bigdigital** [comment]
Hi, not sure this issue is related to watchdrip.  The watchdrip can only put heart rate to the xDrip app, the rest functionality is related to the xdrip itself. Could be the hr sharing is not implemented in xdrip, or you need to enable some option. Would be better to consult in xdrip community.

**Comment by bigdigital** [comment]
https://github.com/NightscoutFoundation/xDrip/issues/1857 found this issue on xdrip git. So close current issue as not related to watchdrip
